name: dio_wrapper
description: Clean http requests.
version: 0.0.2
homepage:

environment:
  sdk: '>=2.19.4 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  dio: ^5.1.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
